### ISSUE TITLE
PDF preview in rendered markdown

### ISSUE THREAD

**Issue by mikicvi** [andrejilderda/joplin-macos-native-theme#100]
Hi,

The PDF preview in rendered markdown is tiny on the Windows desktop app. 

On 100% Joplin scaling, it looks like this on a laptop with a FullHD16:10 aspect ratio (1920x1200 resolution). No custom CSS loaded, just the theme. 

![image](https://user-images.githubusercontent.com/88291034/236887166-ec71fec6-757c-4d3a-8462-72ae2a9ba889.png)

When using the default app a pdf preview looks like this

![image](https://user-images.githubusercontent.com/88291034/236887543-7e5009a3-f27c-4291-b2c7-3327e9de541e.png)

Is there any way to change this behaviour? Maybe through userstyle.css?

**Comment by mikicvi** [comment]
The workaround for this is to edit userstyle.css while targeting the .media-player-media-pdf and changing the min-height element to something like 45rem.

Example below

```
.media-player.media-pdf {
    min-height: 49rem;
}
```

**Comment by andrejilderda** [comment]
Thanks for providing a workaround!
