### ISSUE TITLE
Synchronize button is misplaced

### ISSUE THREAD

**Issue by dabignerd** [andrejilderda/joplin-macos-native-theme#103]
It seems that with the new Joplin update, the Synchronize button has been messed up. It is far too close to the border of the application window, lacking the clean-looking padding that it had before. Here's an image:

![image](https://github.com/andrejilderda/joplin-macos-native-theme/assets/72278628/6830a567-4f1c-4a8e-b9d0-2d714219b646)

**Comment by ScriptInfra** [comment]
Confirmed I am seeing the same:

Joplin v2.11.5
macOS theme v1.3.13

![image](https://github.com/andrejilderda/joplin-macos-native-theme/assets/63025323/2dea3bc9-5fd7-4e2d-bbbd-9bac63927348)

![image](https://github.com/andrejilderda/joplin-macos-native-theme/assets/63025323/2815deef-24de-48c5-b132-a03b19431a7b)

**Comment by andrejilderda** [comment]
This should be fixed in v.1.3.16. Thanks for your patience!
