### ISSUE TITLE
Error in WYSIWYG Editor

### ISSUE THREAD

**Issue by Maghsad** [andrejilderda/joplin-macos-native-theme#105]
Hi Andre,

Thanks for developing this beautiful theme. It seems some bugs need to be tackled to fix the missing item in Japlin's WYSIWYG editor when using this theme.

Here is what is shown when the theme is installed:
<a><img src="https://i.ibb.co/rs6y2Fg/SCR-20230826-nvpc.png" /></a>

Here is what supposed to be shown (is shown without theme):

<a> <img src="https://i.ibb.co/rvWF4TZ/SCR-20230826-nxph.png"/></a>

Thank you.

**Comment by andrejilderda** [comment]
@Maghsad This should be fixed in the latest version (v.1.5.3)!
