### ISSUE TITLE
grey vertical bar at left edge of the MD editor when both macOS theme and Folding in Code Mirror Editor plugins are enabled

### ISSUE THREAD

**Issue by jb261** [andrejilderda/joplin-macos-native-theme#108]
discourse thread describing issue: https://discourse.joplinapp.org/t/anyone-else-have-a-grey-vertical-bar-at-left-edge-of-the-md-editor/33649/3

Folding in Code Mirror Editor v2.0.1 
macOS theme v1.3.13

screenshot showing grey vertical bar:  https://global.discourse-cdn.com/standard14/uploads/cozic/original/3X/e/5/e5a29772acd225d8f173d0c8fa51eaef154eab37.png

**Comment by andrejilderda** [comment]
I can't reproduce this on Joplin v.3.0.6 and the most recent version of this plugin (v.1.5.2). Assuming this is fixed. :) Feel free to reopen if you're still experiencing issues though!
