### ISSUE TITLE
Note listbox is not showing selection

### ISSUE THREAD

**Issue by beatrixwillius** [andrejilderda/joplin-macos-native-theme#109]
Since upgrading to the latest Joplin beta 2.13.6 the note listbox is missing the selection.

Old Joplin:

<img width="938" alt="Bildschirmfoto 2023-11-26 um 06 28 15" src="https://github.com/andrejilderda/joplin-macos-native-theme/assets/1361928/c14636d5-c352-4091-9143-464846fa43c5">

Joplin beta:

<img width="938" alt="Bildschirmfoto 2023-11-26 um 06 29 00" src="https://github.com/andrejilderda/joplin-macos-native-theme/assets/1361928/b3f866c8-faad-4094-ae60-6ae319443d2c">

After making macOS Theme inactive the selection is showing fine.

macOS Theme 1.3.13 on macOS High Sierra and Sonoma 14.2.

**Comment by nelizondo227** [comment]
Same issue. Joplin 2.13.8

**Comment by JetGum** [comment]
Same issue. Joplin 2.13.8 (prod, win32)

**Comment by andrejilderda** [comment]
Hi everyone, as you may have noticed I haven't spend a lot of time on this theme since I'm not using Joplin myself anymore. But this seems like an easy fix so I'll look into this soon. In the meantime feel free to open a PR yourself if you like!

**Comment by kristophercrawford** [comment]
PR for this and issue #110: https://github.com/kristophercrawford/joplin-macos-native-theme/pull/new/issue-110

**Comment by andrejilderda** [comment]
This should be fixed in the latest release.
