### ISSUE TITLE
Joplin release 2.13.9 breaks note list hover/highlight

### ISSUE THREAD

**Issue by kristophercrawford** [andrejilderda/joplin-macos-native-theme#110]
Steps to reproduce the issue: 

1. Have a notebook with at least three notes.
2. Hover over the title of each note in the list.
3. The first note will transition to having a light gray background.
4. The second note in the list will not
5. The third note in the list will.

As an aside, the currently selected note is not highlighted in blue/accent color anymore.

https://github.com/andrejilderda/joplin-macos-native-theme/assets/32402434/90e35b41-5cab-432f-9c69-293557c02bec

**Comment by kristophercrawford** [comment]
PR for this: https://github.com/kristophercrawford/joplin-macos-native-theme/pull/new/issue-110

**Comment by andrejilderda** [comment]
This is indeed not intentional, but the hover for the items should've not been there at all; macOS doesn't use hover states on list items. I'll remove this in a future PR, together with a few more fixes.
