### ISSUE TITLE
Some buttons are not displayed in the Rich Text Editor

### ISSUE THREAD

**Issue by nelizondo227** [andrejilderda/joplin-macos-native-theme#112]
Joplin 2.13.9 (prod, darwin)
macOS theme: 1.3.13

![Screenshot 2023-12-14 at 12 18 30 PM](https://github.com/andrejilderda/joplin-macos-native-theme/assets/52227079/a0e6b8d0-7bb2-46ef-8fa0-bb653bb28597)

The buttons work, but the icon is not displayed.
![Screenshot 2023-12-14 at 12 20 32 PM](https://github.com/andrejilderda/joplin-macos-native-theme/assets/52227079/da12b73d-1e82-48f2-a317-1a738b033364)

Thanks

**Comment by kristophercrawford** [comment]
I have a quick and dirty patch for this:

```
@@ -434,22 +454,37 @@
     button:nth-child(1):before {
       content: "H1";
     }
+
     button:nth-child(2):before {
       content: "H2";
     }
+
     button:nth-child(3):before {
       content: "H3";
     }
-    button:nth-child(4):before {
+  }
+
+  .tox-toolbar__group:nth-child(5) {
+    button:nth-child(1):before {
       @include icon(minus);
     }
-    button:nth-child(5):before {
+  }
+
+  .tox-toolbar__group:nth-child(6) {
+
+    button:nth-child(1):before {
       @include icon(text-quote);
     }
-    button:nth-child(6):before {
+  }
+
+  .tox-toolbar__group:nth-child(7) {
+    button:nth-child(1):before {
       @include icon(tablecells-badge-ellipsis);
     }
-    button:nth-child(7):before {
+  }
+
+  .tox-toolbar__group:nth-child(8) {
+    button:nth-child(1):before {
       @include icon(clock);
     }
   }
```

![image](https://github.com/andrejilderda/joplin-macos-native-theme/assets/32402434/4be6462e-a286-4d0c-9262-20a61cc00428)

But I would like to wait and get some direction on #110 and #111 to see if I am merging these changes in correctly.

**Comment by andrejilderda** [comment]
Thanks @kristophercrawford , that was really helpful!
