### ISSUE TITLE
Add CodeMirror One Dark theme

### ISSUE THREAD

**Issue by kristophercrawford** [andrejilderda/joplin-macos-native-theme#113]
I'd like to try tackling this request: https://discourse.joplinapp.org/t/plugin-macos-theme-for-joplin/18934/114

Could you provide the steps needed to incorporate the theme? I believe the source is this: https://github.com/codemirror/theme-one-dark

**Comment by andrejilderda** [comment]
Hi @kristophercrawford , yes I think you should be able to transform [this TypeScript file](https://github.com/codemirror/theme-one-dark/blob/main/src/one-dark.ts) into a CSS-file like the ones in [this folder](https://github.com/andrejilderda/joplin-macos-native-theme/tree/main/src/css/codemirror). In order for it to show up as an option in the Joplin plugin settings it should be added to `editorMarkdownThemeLught` or `editorMarkdownThemeDark` [here](https://github.com/andrejilderda/joplin-macos-native-theme/blob/bd3f3cbfd4a10b68c6952583c4f2732b0ab6869c/src/index.ts#L141-L227).

**Comment by mikicvi** [comment]
I would absolutely die out of happiness to see this colour scheme added to this project! My absolute favourite one and I am dreading not having it here.

**Comment by mikicvi** [comment]
Is there a specific version of Node that is used for development of this project? 
On `npm run dist` I seem to be getting 
`  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}`

I am getting exactly the same issue on both Windows and Fedora.

**Comment by andrejilderda** [comment]
@mikicvi Yes, I think it's v16 as I need to update some dependencies. 😅

**Comment by kristophercrawford** [comment]
What I am finding is that the one-dark theme from here: https://github.com/codemirror/theme-one-dark/blob/main/src/one-dark.ts doesn't match the one-dark theme on HedgeDoc website. I copied the CSS from the HedgeDoc site and applied it to come up with this:

![image](https://github.com/andrejilderda/joplin-macos-native-theme/assets/32402434/6a4dbdff-608e-43af-a4af-a91845ab6586)

Using the seemingly official style I end up with the following:

![image](https://github.com/andrejilderda/joplin-macos-native-theme/assets/32402434/31ae7ecc-a716-4333-b875-80c001ee719b)
 
So that leaves the question of should the one-dark theme be the seemingly official one or the HedgeDoc implementation of it?

**Comment by andrejilderda** [comment]
@kristophercrawford I personally prefer the second one since it blends in better with the rest of the theme. I think that is also the one @mikicvi took as a base and  implemented in #119. That PR I just merged so should be available in 30 mins when the Joplin bot picks up the change. I assume this issue is solved, so closing this for now. Thanks again @mikicvi!
