### ISSUE TITLE
build css for userchrome.css

### ISSUE THREAD

**Issue by changsijay** [andrejilderda/joplin-macos-native-theme#121]
hi, Could you guilde me how to build CSS which can be copied and paste into userchrome.css?

ex: if I'd like to change
- appearance: light-with-dark-sidebar
- accentColor: purple

and run `npm run build:css` to get the css with above change

**Comment by andrejilderda** [comment]
Hi @changsijay, you don't have to build the css, it's as easy as changing the values in Joplin's settings under 'macOS theme'. ;)

**Comment by changsijay** [comment]
yes, if i install plugin and change settings it looks as i like.

but after installed macos theme plugin, my customized userstyles.css for markdown rendering stop work.

that's what i tried using the generated css directly, and by this way, my customized userstyles.css works fine too.

so i am wondering if i can use this way with some default value changed and also it is easy to do more customization too

**Comment by gresces** [comment]
I want to change the background color of rendered code block. 
But changes in `userstyles.css` are useless!
I just want the bkg color to be lighter! :-)

**Comment by changsijay** [comment]
as I check `com.andrejilderda.macOSTheme.jpl` below part,
could I override this part by `userstyles.css` ?
because the color looks not that good on markdown preview

<img width="536" alt="image" src="https://github.com/andrejilderda/joplin-macos-native-theme/assets/245306/93f80545-b331-4a22-809f-1850b69ef151">


```
@media screen and (prefers-color-scheme: dark) {
  body#tinymce pre:not(.mermaid),
body#tinymce .inline-code,
#joplin-container-content pre:not(.mermaid),
#joplin-container-content .inline-code {
    background-color: rgba(var(--g-shadowColor--rgb), 0.2);
  }
}
```

**Comment by gresces** [comment]
> as I check `com.andrejilderda.macOSTheme.jpl` below part, could I override this part by `userstyles.css` ? because the color looks not that good on markdown preview
> 
> ```
> @media screen and (prefers-color-scheme: dark) {
>   body#tinymce pre:not(.mermaid),
> body#tinymce .inline-code,
> #joplin-container-content pre:not(.mermaid),
> #joplin-container-content .inline-code {
>     background-color: rgba(var(--g-shadowColor--rgb), 0.2);
>   }
> }
> ```
> 
> example screenshot <img alt="image" width="536" src="https://private-user-images.githubusercontent.com/245306/293498101-93f80545-b331-4a22-809f-1850b69ef151.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMTUxMzEsIm5iZiI6MTcwNDAxNDgzMSwicGF0aCI6Ii8yNDUzMDYvMjkzNDk4MTAxLTkzZjgwNTQ1LWIzMzEtNGEyMi04MDlmLTE4NTBiNjllZjE1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMVQwOTI3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzEzZTEyNjNjOTYyNjMyOWMyNGU2MDRmZjAzNDY4YmI3N2FjODI0OGMwNTdkMzcxY2RjYWU1OWU0Y2Q2M2I0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cz3WaipxWYkSUUDdcTZXa0QTTcOCqoOhtc4DHi0Lt28">

I tried add '!important' at the end of lines. It's useful but I dislike this way.
```css
@media screen and (prefers-color-scheme: dark) {
  body#tinymce pre:not(.mermaid),
body#tinymce .inline-code,
#joplin-container-content pre:not(.mermaid),
#joplin-container-content .inline-code {
    background-color: rgba(var(--g-shadowColor--rgb), 0.05) !important;
  }
}
```

**Comment by changsijay** [comment]
now i am trying comment out this part in 
https://github.com/andrejilderda/joplin-macos-native-theme/blob/main/src/scss/components/_components.tinyMCE.scss#L93

and npm dist to build and use the plugin locally.
then my userstyles.css works well now :)
tho still wish have chance to use official plugin from here without local build.

<img width="449" alt="image" src="https://github.com/andrejilderda/joplin-macos-native-theme/assets/245306/5b022138-035b-493b-a534-968f7201b23e">

<img width="1369" alt="image" src="https://github.com/andrejilderda/joplin-macos-native-theme/assets/245306/1f0cec73-75f0-4a8e-b995-06167fe4f33a">

**Comment by andrejilderda** [comment]
The theme styles unfortunately contain a lot of `!important`'s because of the way the styles in Joplin are setup. There are nicer, more modern ways to handle this (cascade layers), but Joplin's base styles don't make use of this. This means for now there are no easy ways to override styles set by Joplin nor this theme and slapping some more !important's is the way to go.
