### ISSUE TITLE
Checked Checkboxes do not strike threw or grey out

### ISSUE THREAD

**Issue by fishooo0815** [andrejilderda/joplin-macos-native-theme#122]
I very sorry. I can not Upload a screenshot.

I expect 
- [x] text  <--- should be greyed out or striked threw in preview mode. but it is white text.

**Comment by andrejilderda** [comment]
Hmm... can't replicate. Maybe it helps to switch the Markdown theme? More info: https://github.com/andrejilderda/joplin-macos-native-theme/issues/99#issuecomment-1871427307

**Comment by lzambarda** [comment]
Facing the same issue, running version v1.5.14.

<img width="179" alt="Image" src="https://github.com/user-attachments/assets/a93c4e5a-d62d-410e-a362-fa909a83f2cc" />

Note: I am also running Rich Markdown v0.16.0.
