### ISSUE TITLE
Layout and Typography look inconsistent with Note List Preview Plugin

### ISSUE THREAD

**Issue by luigicarrini** [andrejilderda/joplin-macos-native-theme#123]
Hi,

When I enable the new [note list preview plugin](https://github.com/JackGruber/joplin-plugin-notelistpreview), the layout and typography of the note list plugin look very inconsistent with the MacOS theme.

Would it be possible to adjust the MacOS theme plugin so it supports the new note list preview layout and everything looks consistent? 

MacOS theme plugin v1.3.18
Joplin Desktop App 2.13.11

**Comment by andrejilderda** [comment]
Hi @luigicarrini, I don't plan on adding support for the plugin mentioned, but am open to PR's!
