### ISSUE TITLE
Versions ≥1.3.15 missing note list highlight color with Joplin ~2.9

### ISSUE THREAD

**Issue by ernstki** [andrejilderda/joplin-macos-native-theme#125]
@andrejilderda, nothing here requires your attention, because I'm using an old and probably unsupported version of Joplin, and the correct answer is probably just "update Joplin" However, I am stubborn and didn't want to. 

I thought this would be a fun thing to try and puzzle out, and I'm just documenting the process for posterity—in case any other upgrade-averse weirdos end up in this situation—after which I'll close the issue.

Thanks for your efforts making this stellar theme!

## The problem

The active note in the notes list is missing the highlight color, with the macOS theme, blue highlight, light mode in main Joplin settings (Joplin 2.9.17).

![Animated GIF showing the act of selecting one note and then the other -- there is no highlight color](https://github.com/andrejilderda/joplin-macos-native-theme/assets/4009681/3aa6baa6-c490-400a-bf90-205a86b44c2e)

I had been running 1.3.13 of the `joplin-macos-native-theme` plugin. I want to revert to that version, but as explained [in this Joplin forum post](https://discourse.joplinapp.org/t/reinstalling-an-old-version-of-a-plugin/25590/2), that can be tricky, unless the `.jpl` file is published as an asset alongside the GitHub releases, which not all plugin projects do.

(No judgements—these are free-time hobby projects!)

## Context

Somewhere around release 1.3.15, probably to keep pace with a Joplin update, the CSS for the selected note in the notes list was changed in a way that was backward-incompatible with Joplin circa 2.9.

There are no [tagged releases](https://github.com/andrejilderda/joplin-macos-native-theme/releases) earlier than 1.3.15, so some digging in the Git history was required.

Another wrinkle is that I use an LTS version of an Ubuntu-based OS (elementaryOS Jólnir), whose `nodejs` package tops out at 10.something. I don't _need_ Node.js, so I'm resistant to installing any more packages _just_ to build this one `.css` file. Life is far too short to go down another JavaScript rabbit-hole unless absolutely necessary.

This is a job for Docker.

## Workaround

```console
$ cd ~wherever/you/put/source/code
$ git clone https://github.com/andrejilderda/joplin-macos-native-theme.git

$ git log --oneline | grep 'Initial commit'  # where to start (ba898c3 - Initial commit)

$ git log -L 1,5:package.json ba898c3..v1.3.15  # find 1.3.13 (0c6ba0e)

$ docker run --rm -it --user=$UID -v .:/src node:12-slim \
              bash -c 'cd /src && npm install && npm run dist'
```

Then note the path to `publish/com.andrejilderda.macOSTheme.jpl` and install that within Joplin:

![Animated GIF showing the process for installing the `.jpl` file in Joplin's settings](https://github.com/andrejilderda/joplin-macos-native-theme/assets/4009681/a0a9d29c-53f1-4070-94b3-e9683c6cdf67)

## Helpful links

* [Reinstalling an old version of a plugin](https://discourse.joplinapp.org/t/reinstalling-an-old-version-of-a-plugin/25590) - locked Joplin Discourse thread without a solution that helped me, but at least inspired me to _try_
* [ReferenceError: globalThis is not defined](https://stackoverflow.com/questions/66586352/referenceerror-globalthis-is-not-defined/66587789#66587789) - _stackoverflow.com_
* https://github.com/arkark/git-hist - helped me find the commit that introduced v1.3.13, by examining the changes to `package.json` (it was 0c6ba0e)
  * …though I later discovered that `git log -L 1,5:package.json` accomplishes nearly the same thing

**Comment by ernstki** [comment]
Closing as stated in the description above.

**Comment by andrejilderda** [comment]
Thanks @ernstki for figuring this out and documenting this. 👌 

For getting the .jpl's of older versions of this plugin this is the easy way:

- look up the [version number here](https://www.npmjs.com/package/joplin-plugin-macos-theme?activeTab=versions)
- Navigate to https://registry.npmjs.org/joplin-plugin-macos-theme/{VERSION-NUMBER-HERE} (or go the next step directly)
- And open the link under dist/tarball, f.e. https://registry.npmjs.org/joplin-plugin-macos-theme/-/joplin-plugin-macos-theme-1.3.18.tgz

This will download a tarball you can unzip that contains the .jpl-file in the publish folder.

**Comment by ernstki** [comment]
> This will download a tarball you can unzip that contains the .jpl-file in the publish folder.

Ha! I suspected that might be the case, but this was good training. `;)`

Thanks again, love the theme, and appreciate all the work you and contributors have done keeping it going.
