### ISSUE TITLE
Cant change editor font size

### ISSUE THREAD

**Issue by elesto** [andrejilderda/joplin-macos-native-theme#46]
Hi, the theme seems to override css settings. How would I go about changing editor font side in the userchrome
This doesnt work:

`
#rendered-editor {
font-size: 13pt !important;
font-family: "Times New Roman" !important;
}
`

**Comment by andrejilderda** [comment]
Hi @friendlytherapist , you're probably looking for:
`#rendered-md { ... }` in stead of `#rendered-editor`

**Comment by elesto** [comment]
Hi, im trying to change the font size for the editor. Currently when the mac theme is installed the editor font size setting in appearance doesn't change anything. And changing the font size in the mac theme panel will change the size of all fonts app wide. I have figured out how to change the markdown font size with `#rendered-md` but there is no way to set editor font size separately from system wide font size.

**Comment by prlhspt** [comment]
In my case, I solved it by applying this.

```css
.CodeMirror pre.CodeMirror-line{
	font-size: 1.2em !important;
}
```

**Comment by elesto** [comment]
Thanks that works great
