### ISSUE TITLE
Grey background to a portion of the toolbar

### ISSUE THREAD

**Issue by mrkrsl** [andrejilderda/joplin-macos-native-theme#47]
Much of the toolbar in the non-MD editor (everything to the right of the external editing button and to the left of the editor toggle) is rendered with a grey background. This is at odds with the rest of the theme.

See this example screenshot of the toolbar area:
![image](https://user-images.githubusercontent.com/349371/148217659-c6be0dd3-7162-4c4b-9456-3547f03614ba.png)

**Comment by andrejilderda** [comment]
Thanks for reporting this @mrkrsl , I've just pushed an update that should fix this (available in around 20 min). Feel free to reopen if it does not work for you!
