### ISSUE TITLE
Activated Theme slows down Joplin

### ISSUE THREAD

**Issue by reaseno** [andrejilderda/joplin-macos-native-theme#48]
When I use the theme, the typed text takes some time between typing on the keyboard and appearing on the screen until it becomes visible, which makes typing a bit annoying. The positioning of the cursor is also delayed.

**Comment by andrejilderda** [comment]
Hi @reaseno, are you sure this is because of the theme? It doesn't do much except for injecting styles. Don't you notice this when the theme is disabled?

**Comment by reaseno** [comment]
Ah right, I wanted to write you that I'm analyzing the problem, since it seems to happen also when I paste your CSS manually. But I don't think it's because of the CSS itself. So it's probably not your module.

But at least Joplin starts much faster when the module is disabled and your CSS is inserted via userchrome.css. Wouldn't it be better if the module did it that way too?

**Comment by andrejilderda** [comment]
@reaseno I've made [this change](https://github.com/andrejilderda/joplin-macos-native-theme/commit/94ee048a87f7d1da318aeca8fc9e738447605249) in v.1.2.17 of the plugin and I'm curious if you notice any difference.

**Comment by andrejilderda** [comment]
Fyi, it removes the loading of an svg-file which was 5 mb. big. 😅

**Comment by andrejilderda** [comment]
@reaseno Ah great to hear, closing this!
