### ISSUE TITLE
[Question] Can dim a little for the light color?

### ISSUE THREAD

**Issue by dunmorogher** [andrejilderda/joplin-macos-native-theme#49]
Hello Author!

I'm now using macOS theme with Dark Appearance set. But I feel like it's just a little glaring for those white color, like below: 

![圖片](https://user-images.githubusercontent.com/41850822/149721020-c729888e-2c5a-473b-af6c-eeb2d27e2221.png)

So, if I want to change the white color to be dimmer, like to be white-gray, should I only modify the source code and build the plugin by my own? 

Thanks in advance! :-)

**Comment by andrejilderda** [comment]
Hi @dunmorogher , you should be able to override the `--g-textColor`-custom property in the `userStyle.css`, which you can access via Joplin › Appearance › Show Advanced Settings › 'Custom stylesheet for rendered Markdown'.

The following should work: 

```css
:root:root {
  --g-textColor: #ccc;
}
```

**Comment by dunmorogher** [comment]
> Hi @dunmorogher , you should be able to override the `--g-textColor`-custom property in the `userStyle.css`, which you can access via Joplin › Appearance › Show Advanced Settings › 'Custom stylesheet for rendered Markdown'.
> 
> The following should work:
> 
> ```css
> :root:root {
>   --g-textColor: #ccc;
> }
> ```

Oh great! Thanks @andrejilderda! Well resolved, it's pretty comfortable with dark environment... By the way, are this kind of variables, like "--g-textColor" have been mentioned in Joplin's official website? :-)

**Comment by andrejilderda** [comment]
You're welcome!

No the variables are not on the official Joplin website, because they're not official (they are part of the theme). 😁

**Comment by dunmorogher** [comment]
> You're welcome!
> 
> No the variables are not on the official Joplin website, because they're not official (they are part of the theme). 😁

Oh alright alright! Anyways, thanks a lot @andrejilderda! 😁
