### ISSUE TITLE
**Bold** & *Italics* in MarkDown Editor?

### ISSUE THREAD

**Issue by MrPoetry** [andrejilderda/joplin-macos-native-theme#51]
I'm wondering if there is a way to get the MD editor to display **bold** & *italics* in, respectively, heavier font-weight and slanted font-style -- like, say TextMate? I simply don't recall, from before installing this plugin, whether this is something Joplin's MD editor even does in the first place.

**Comment by andrejilderda** [comment]
Hi @MrPoetry , take a look at this [Rich Markdown](https://github.com/CalebJohn/joplin-rich-markdown#readme)-plugin. With `Tools -> Options -> Rich Markdown -> Add additional CSS classes for enhanced customization` with some user styles you should be able to make this work. The [Extra CSS](https://github.com/CalebJohn/joplin-rich-markdown/blob/main/README.md#extra-css)-part in the README has info about the classnames you can target. 

If you need any help, drop a line!

**Comment by MrPoetry** [comment]
I installed Rich Markdown, which seemed to have no option for MD-editor display of bold & italics, so I opened an issue on that plugin's github page, asking if I was missing something. Here is that dev's reply:

> > Am I missing something?
> 
> Just that italics and bold styling is not a feature of this plugin. That's actually a feature of the base application (below is a screenshot from a clean version of Joplin without any plugins).
> 
> ![image](https://user-images.githubusercontent.com/2179547/150477813-cc837cae-49a8-4054-8aff-6c71286a41cd.png)
> 
> ***The macos-native-theme plugin overrides the Joplin css. You'll need to ask that plugin developer to add the styles you want back in***…. [emphasis added by me]

I'm not sure how to approach the issue now. In case it's playing a role in the problem, I do use a userchrome.css, which only consists of:

.ace_content {
    font-size: 20px;
    /* changes the font size of the ACE editor body text */
}

span[role="presentation"] {
	font-size: 20px;
	/* changes the font colour for the editor text */
}

Do you have any thoughts about what might be going on?

**Comment by MrPoetry** [comment]
NEVER MIND: Ignore previous comment! Suddenly **bold** and *italics* are rendering in the MD editor. I ***swear*** it wasn't working an hour ago.

**Comment by andrejilderda** [comment]
@MrPoetry Ha no worries! Glad to hear it's working. 👍
