### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by ianchanning** [andrejilderda/joplin-macos-native-theme#52]
Hi there, I love this theme - especially useful is the [userrchrome CodeMirror css themes](https://github.com/andrejilderda/joplin-macos-native-theme/tree/main/src/css/codemirror).

However you don't currently specify a license for this repository - I assume this is open source but without the license it is by default not available to copy.

**Comment by andrejilderda** [comment]
Hi Ian, good one, here ya go!
https://github.com/andrejilderda/joplin-macos-native-theme/blob/main/LICENSE

Regarding the Codemirror CSS themes, you can also get them from:
https://github.com/codemirror/CodeMirror/tree/master/theme (MIT also)

**Comment by ianchanning** [comment]
Awesome - thank you!
