### ISSUE TITLE
Use white backgrounds for mermaid diagrams

### ISSUE THREAD

**Issue by ianchanning** [andrejilderda/joplin-macos-native-theme#55]
Hi there,

I'm using Joplin on Linux and I was trying some [mermaid diagrams](https://joplinapp.org/markdown/#diagrams) yesterday. Your theme uses a grey background which conflict with the diagrams making the grey arrows hard to see. Here's two screenshots one with your theme and one with the base 'Light' theme. 

See this comment from the mermaid diagrams docs above:

> Note that Mermaid graphs are always rendered on a white background regardless of the current theme. This is because they can contain various colours that may not be compatible with the current theme.

Mac OS theme
![Screenshot from 2022-02-14 16-15-43](https://user-images.githubusercontent.com/233318/153891994-74d865d3-8dd9-4ad6-8f32-8d6d3e17e804.png)

Default Light theme
![Screenshot from 2022-02-14 16-16-40](https://user-images.githubusercontent.com/233318/153892035-c4268f5a-3dbc-4fca-8517-eaf72da3b184.png)

**Comment by andrejilderda** [comment]
Hi @ianchanning , I've just pushed an update that should fix your issue. It will be picked up by the [Joplin bot](https://github.com/joplin/plugins/) in around 30 mins.. Let me know if it works for you!

**Comment by ianchanning** [comment]
Yes, awesome it works! Thank you :) 
![Screenshot from 2022-02-25 11-40-24](https://user-images.githubusercontent.com/233318/155701369-bfa4793d-129b-475b-b43c-08c03b0e9071.png)
