### ISSUE TITLE
如何自定义字体呢，在css里修改了，但是生成的不变

### ISSUE THREAD

**Issue by abcmiao** [andrejilderda/joplin-macos-native-theme#56]
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/13944985/154394856-33cb915a-6048-47e2-bc6a-d9e51dca1010.png">

关闭主题就可以显示了，主题默认只有苹方字体和另一个可以选

**Comment by andrejilderda** [comment]
I believe there was no option to select a different font in Joplin's settings when I made this theme, so it overrides it on several places. You can however change that by adding the following to your `userstyle.css`:

```
body {
  --s-font-family-system: '<FONT FAMILY NAME>';
}
```

Let me know if that works for you!
