### ISSUE TITLE
UI Issue on Note List Sidebar

### ISSUE THREAD

**Issue by hpradogu** [andrejilderda/joplin-macos-native-theme#57]
Hello!

thanks for creating this theme! I just downloaded it today, and absolutely love it.

I did notice a minor issue with the UI after installing, however.

Joplin version 2.7.12
macOS 12.2.1

You can see that the search and the sorting (and the other icons) are now squished together in the corner.

<img width="184" alt="Screen Shot 2022-02-17 at 14 00 15" src="https://user-images.githubusercontent.com/12103688/154577994-b9aacf29-50a4-430e-86ca-f06baa0c3933.png">

**Comment by andrejilderda** [comment]
Hi @hpradogu , this only happens if you have the sidebar set to a very small width, don't you? In that case, the solution would be to increase it. 😉

**Comment by hpradogu** [comment]
# Original Issue
Yes, you are correct.
However, I'm running Joplin on my iPad as my second monitor, so my resolution isn't that great (so things generally need to be smaller).

When I run custom CSS styling, I don't have this particular issue, and it seems like the stock Dark Joplin theme handles it decently.

See the behavior with custom CSS styling (there's a minimum width set:
https://user-images.githubusercontent.com/12103688/155187243-d5b569e3-84a5-4fb4-a843-3f0a90db23aa.mov

Here's the **stock Joplin dark theme** behavior :
https://user-images.githubusercontent.com/12103688/155188046-b6562c03-fcac-4648-9230-859055a7a44e.mov

Here's the behavior with the **macOS** theme:
https://user-images.githubusercontent.com/12103688/155187958-8b8c834f-a43c-4914-973c-25212f8fbda4.mov

# New Issue
I'm having another (different issue) related to UI. Not sure
 if you've seen this:
<img width="1019" alt="Screen Shot 2022-02-22 at 09 33 57" src="https://user-images.githubusercontent.com/12103688/155186837-51f5861b-77c4-4233-ab30-b150b090f57e.png">
**All the icons are now just squares. All other plugins are turned off.**

**Comment by andrejilderda** [comment]
Thanks for the detailed report! I've just pushed a change which should fix your issue. 

Regarding the icons, do you maybe have it set to `macOS native (SF Pro)` in the plugin settings, while not having SF Pro installed? [See the installation instructions here](https://github.com/andrejilderda/joplin-macos-native-theme#no-icons).

![screenshot 2022-02-25 at 21 22](https://user-images.githubusercontent.com/487182/155796403-b5368249-2c49-411e-ac65-32e574a176ec.png)

**Comment by andrejilderda** [comment]
@hpradogu Here's a screencap :)

https://user-images.githubusercontent.com/487182/155799790-920d2738-8ece-406c-bbf1-0eb1f1259fa2.mov
