### ISSUE TITLE
Reminder CSS when setting time

### ISSUE THREAD

**Issue by pschopen** [andrejilderda/joplin-macos-native-theme#58]
<img width="561" alt="grafik" src="https://user-images.githubusercontent.com/65334274/154837691-2d0bf1f2-df52-4b4e-89dc-c982dd5b82c0.png">

seems that some settings with the container are wrong.

**Comment by pschopen** [comment]
I added the following code to my custom css which solved the issue. 

.rdtPicker td, .rdtPicker th {
  height: auto;
}

**Comment by andrejilderda** [comment]
@pschopen Thanks for noticing Philip! This should be fixed in the next update. Feel free to reopen if that is not the case. 👍
