### ISSUE TITLE
Icons in sidebar too large

### ISSUE THREAD

**Issue by pschopen** [andrejilderda/joplin-macos-native-theme#59]
The icons in the left sidebar are not themed, I guess. They are way too large compared to the text. This is the custom css that solved it for me. 

#react-root > div > div > div.resizableLayoutItem.rli-root > div.resizableLayoutItem.rli-sideBar > div > div > div > div.folders.expanded > div > a > span{
    font-size:10px !important;
    margin-right: 5px !important;
}

#react-root > div > div > div.resizableLayoutItem.rli-root > div.resizableLayoutItem.rli-sideBar > div > div > div > div.folders.expanded > div > a > span.title{
    font-size:1.3rem !important;
}

**Comment by andrejilderda** [comment]
Hmm... Which Joplin version are you using @pschopen ? Can you share a screenshot?

**Comment by pschopen** [comment]
![grafik](https://user-images.githubusercontent.com/65334274/154853139-7c0f2b44-0ae3-4e77-ba6c-dd32eb9269b8.png)

After adding the CSS it looks like this.

![grafik](https://user-images.githubusercontent.com/65334274/154853184-eea0fdbe-bf37-4884-ac3c-00ebdf06eae8.png)

**Comment by andrejilderda** [comment]
@pschopen Ah I see, that is a new feature that I wasn't aware of. I changed the size slightly in the next update.
