### ISSUE TITLE
Shared Notebook Icon Broken

### ISSUE THREAD

**Issue by ScriptInfra** [andrejilderda/joplin-macos-native-theme#62]
Joplin Version 2.7.13
MacOS Plugin Version 1.2.17

Appreciate the continued updates on this plugin! I wanted to bring to your attention that there appears to be an issue with the icon when a notebook is shared (I am sharing via Joplin Server). I think less important, but also notable is that there is a color distinction between shared and unshared notebooks.

Below is a screenshot without the MacOS plugin:
![image](https://user-images.githubusercontent.com/63025323/155969125-9230eae7-473f-415e-ac4f-bd30384f6a3d.png)

Below is a screenshot with the MacOS plugin:
![image](https://user-images.githubusercontent.com/63025323/155969290-ea76c68b-4d80-45bb-8926-79eacd8587ba.png)

**Comment by andrejilderda** [comment]
Hi @ScriptInfra , I've just pushed an update that should fix your issue. Will you let me know if it works for you?

**Comment by ScriptInfra** [comment]
Hi @andrejilderda - I've tested this update on both MacOS and Ubuntu Linux, and both look great. Thanks so much for the update!
