### ISSUE TITLE
Table Properties Options Difficult to View

### ISSUE THREAD

**Issue by ScriptInfra** [andrejilderda/joplin-macos-native-theme#66]
Hello! When selecting 'Table properties' in an existing table, the unselected option is very difficult to see using the following settings:

MacOS Theme:
Appearance: Dark
Markdown editor light: base16-light
Markdown editor dark: base16-dark

Joplin App:
Theme: Dark

Kindly see the following screenshot, where 'Advanced' is difficult to see:

![image](https://user-images.githubusercontent.com/63025323/163651635-fd4c63c7-f324-4c94-929c-8d0cb399ec73.png)

Switching to the 'Advanced' selection, 'General' is now difficult to see:

![image](https://user-images.githubusercontent.com/63025323/163651754-5d8743a4-3084-4b6b-b17d-d3cb40fe553f.png)

**Comment by andrejilderda** [comment]
Hi @ScriptInfra, I've changed the styling a bit to look a bit more macOS'ey which should solve your issue:

<img width="571" alt="image" src="https://user-images.githubusercontent.com/487182/165378266-33936ed3-f10d-403f-8141-46ad08601ea2.png">

**Comment by ScriptInfra** [comment]
Hi @andrejilderda - Thanks so much for looking into this. I updated the plugin and it looks great on my end as well now!
