### ISSUE TITLE
Border Color Sized Incorrectly

### ISSUE THREAD

**Issue by ScriptInfra** [andrejilderda/joplin-macos-native-theme#67]
Hello! The border color selection "square" does not fit properly within the UI as shown below:

MacOS Theme disabled:
![image](https://user-images.githubusercontent.com/63025323/163653254-d5ab5f8e-c823-4ccb-8b3e-f3e165da8dda.png)

MosOS Theme enabled:
![image](https://user-images.githubusercontent.com/63025323/163653361-153a6a55-6175-4b94-8f96-b44ff6d8d012.png)

**Comment by andrejilderda** [comment]
Hi @ScriptInfra, I've changed the styling a bit to look a bit more macOS'ey which should solve your issue:

<img width="571" alt="image" src="https://user-images.githubusercontent.com/487182/165378266-33936ed3-f10d-403f-8141-46ad08601ea2.png">

**Comment by ScriptInfra** [comment]
Hi @andrejilderda - Thanks so much for looking into this. I updated the plugin and it looks great on my end as well now!
