### ISSUE TITLE
Shortcut to note title scrolls editor pane to right 

### ISSUE THREAD

**Issue by graphit0** [andrejilderda/joplin-macos-native-theme#68]
A minor visual bug due to small screen size or large zoom. It looks like a theme bug, because it doesn't happen without macOS theme, so I'm wondering if you could replicate it

## Short description

Focusing on note title using a shortcut causes markdown editor pane to shift to the right

https://user-images.githubusercontent.com/44114323/164799041-63d0e41f-3729-425c-9f0a-ff82a8424e0e.mp4

## Environment
Joplin 2.7.15 (prod, linux)
Platform: Linux
OS specifics: Kubuntu 21.04

## Steps to reproduce

1. Resize window till it's small enough to move the "tool bar on the side of note title" to the next line
![image](https://user-images.githubusercontent.com/44114323/164800860-b019e9cd-4cd8-474c-9b3c-483b33b454f6.png)
:arrow_right: 
![image](https://user-images.githubusercontent.com/44114323/164801617-0437ec57-0ea5-4f98-b5c5-1cb6c044cc50.png)
2. Focus on note body 
2. Press shortcut to focus on the note title

## Actual result
Editor pane-view has been scrolled slightly to the right. It remains in this state while switching notes in the same notebook. It can be mitigated by expanding the window size or changing a notebook (reloading editor).

The effect can be seen in markdown previewer and WYSIWYG but due to margins it doesn't hide the first letter in a line.

## Describe what you expected to happen
Editor pane remain at the same view position as before

## Logfile
Executing note-title-focus shortcut produces the following line in the console
```
CommandService::execute: focusElementNoteTitle
```

**Comment by andrejilderda** [comment]
Thanks for your detailed issue @graphit0 ! I managed to recreate your issue with your instructions. It should be fixed with the new version. Let me know if it doesn't.
