### ISSUE TITLE
'New note' Prompt Not Distinct

### ISSUE THREAD

**Issue by ScriptInfra** [andrejilderda/joplin-macos-native-theme#70]
Hello! I noticed that under the following conditions, the following text is difficult to read:

Text: No notes in here. Create one by clicking on "New note".

Settings: MacOS theme light with dark sidebar; 'Dark' Theme under the Appearance tab (Joplin setting)

Reproduce: This text can be located by clicking on an empty notebook.

Screenshot:

![image](https://user-images.githubusercontent.com/63025323/165385903-9c819aab-3343-4971-af83-18a303ece39f.png)

**Comment by andrejilderda** [comment]
Hi @ScriptInfra , this should be fixed in 1.3.3. :)
