### ISSUE TITLE
Apply Markdown Editor Color to the WYSIWYG Editor

### ISSUE THREAD

**Issue by ScriptInfra** [andrejilderda/joplin-macos-native-theme#74]
Hello! Thanks as always for the great work on this plugin.

Would it be possible to apply the Markdown editor color to the WYSIWYG editor? Currently, changing the Markdown editor color results in the below.
In my humble opinion, applying different colors to the Markdown and WYSIWYG editors breaks up a lot of fluidity in the app and additionally makes it difficult for me to read content in the WYSIWYG editor.

![image](https://user-images.githubusercontent.com/63025323/170069743-28ae03fa-6912-4459-be5e-bf647b6664f7.png)

**Comment by andrejilderda** [comment]
@ScriptInfra How did you get the background color to differ? Custom styles?

**Comment by ScriptInfra** [comment]
@andrejilderda - Took me a minute to figure out how to reproduce this..

Setting the 'Dracula' theme with the macOS 'Light with dark sidebar' theme, results in the following:

![Screenshot 2022-12-22 at 12 10 51 AM](https://user-images.githubusercontent.com/63025323/209061645-5987c9ce-f570-4f75-9a82-6bebe37e10e5.png)


Strangely, I found that the following themes did not encounter this issue:

- Solarized Light
- Solarized Dark
- Nord
- Atrium Dark
- OLED Dark

Any thoughts on why this might be the case? I wonder if it's possible to fix this with the 'Dracula' theme?

**Comment by andrejilderda** [comment]
Thanks @ScriptInfra! I've updated [this README section](https://github.com/andrejilderda/joplin-macos-native-theme#installation) so that it states to keep Joplin's default theme set to either 'Light' or 'Dark'.

**Comment by ScriptInfra** [comment]
Perfect, thank you!
