### ISSUE TITLE
Add Gray Appearance Option

### ISSUE THREAD

**Issue by ScriptInfra** [andrejilderda/joplin-macos-native-theme#75]
Could we please add a new gray color scheme to the plugin? Personally, I find the Dark mode exceedingly hard on the eyes. To the contrary, I really like the gray color as it's seen in the 'Light with dark sidebar' color as seen below. Maybe we could extend the gray color to the rest of the UI in a slightly lighter shade of gray? (similar to how the Light scheme uses a slightly different shade of white for the Notebook bar.)

![image](https://user-images.githubusercontent.com/63025323/170086587-b76ef016-8cc6-4942-82aa-d7f22b930dfc.png)

From a UI/color perspective this would be similar to the gray theme from Microsoft Outlook. Some screenshots of that can be found here: https://answers.microsoft.com/en-us/outlook_com/forum/all/new-outlook-dark-gray-theme-is-broken-looks-awful/c8268394-4113-4938-acca-5caef680bd0c?auth=1

**Comment by andrejilderda** [comment]
My eyes 🙈 j/k. I don't plan on supporting an extra color palette. But if you are comfy with CSS and want to get creative yourself you can change the colors by overriding the CSS custom properties:

```css
:root:root {
  --foobar: #ccc;
}
```
