### ISSUE TITLE
Replace folder icons with emojis if present

### ISSUE THREAD

**Issue by nblumoe** [andrejilderda/joplin-macos-native-theme#77]
If a notebook title starts with an emoji, it would be great if the folder icon could be replaced by the emoji. Currently one gets a folder icon and the emoji:

<img width="162" alt="CleanShot 2022-05-30 at 18 32 28@2x" src="https://user-images.githubusercontent.com/995628/171032219-e7faf21a-2908-4b85-9713-6ac678b9b979.png">

Before starting to use the macOS theme, I added these emojis, because they actually look like nice, folder icons in the default theme (there is no special treatment there though, it's just a normal character in the notebook title):
<img width="162" alt="CleanShot 2022-05-30 at 18 33 30@2x" src="https://user-images.githubusercontent.com/995628/171032819-f4b0272c-be12-4464-b18a-40a4c8c1d8e7.png">

**Comment by andrejilderda** [comment]
Good one @nblumoe . This should work nicely in the latest version.
