### ISSUE TITLE
Expand Notebook Arrow Icon is not Centered

### ISSUE THREAD

**Issue by ScriptInfra** [andrejilderda/joplin-macos-native-theme#82]
Hello! I noticed that with the theme applied, the expand arrow icon is slightly raised above where it should be:

Slightly raised too high:
<img width="331" alt="Screen Shot 2022-09-21 at 9 46 41 AM" src="https://user-images.githubusercontent.com/63025323/191521230-e14c8762-3c9a-4b7b-b82c-8a6485298381.png">

Expected Alignment with the Notebook Name:
<img width="338" alt="Screen Shot 2022-09-21 at 9 48 22 AM" src="https://user-images.githubusercontent.com/63025323/191521506-8887df8d-f4e3-483d-a506-9473ce8e9837.png">

**Comment by ScriptInfra** [comment]
Hey @andrejilderda - Just wanted to bump this bug to see if you might have an idea when this might be resolved? Thanks so much.

**Comment by andrejilderda** [comment]
@ScriptInfra Should be fixed in the latest version!
