### ISSUE TITLE
Emoji Malformed

### ISSUE THREAD

**Issue by ScriptInfra** [andrejilderda/joplin-macos-native-theme#86]
Joplin v2.9.17
macOS theme v1.3.5

Hello! It appears that the emojis have a strange white border around them and are not quite sized properly to fit within the space:

![image](https://user-images.githubusercontent.com/63025323/208138920-454d1187-0e45-49e3-a71c-0dcf5e429ca5.png)

![image](https://user-images.githubusercontent.com/63025323/208139280-a2c6654f-6da7-406a-8aef-37fb9a6e3649.png)

**Comment by andrejilderda** [comment]
Hi @ScriptInfra , [here I see a screenshot](https://github.com/andrejilderda/joplin-macos-native-theme/issues/89) which doesn't have the problem. Is this issue still relevant?

**Comment by ScriptInfra** [comment]
Hi @andrejilderda  - After some further testing I think this might still be an issue, specifically with the 'Light with dark sidebar' set. I tested the following theme combinations:

Joplin theme: Dark
macOS theme: Dark
Issue not present

Joplin theme: Light
macOS theme: Light
Issue not present

Joplin theme: Light
macOS theme: Dark
Issue not present

Joplin theme: Dark
macOS theme: Light
Issue not present

Joplin theme: Light
macOS theme: Light with dark sidebar
Issue present

Joplin theme: Dark
macOS theme: Light with dark sidebar
Issue present

**Comment by ScriptInfra** [comment]
Screenshot from macOS theme v1.3.9:

![Screenshot 2022-12-21 at 5 40 36 PM](https://user-images.githubusercontent.com/63025323/209016409-9801fd80-73ed-4b68-9dd0-fbaa5c482ee3.png)

**Comment by andrejilderda** [comment]
Aha ok, that helps. 👍 Thanks for investigating.

**Comment by andrejilderda** [comment]
This should be fixed in v.1.3.11!

**Comment by ScriptInfra** [comment]
Looks good on my end. Thank you!
