### ISSUE TITLE
joplin UI is blank when using joplin version 2.9.17

### ISSUE THREAD

**Issue by SuzanneHuang** [andrejilderda/joplin-macos-native-theme#87]

**Comment by SuzanneHuang** [comment]
Hi,
I have found this plugin will cause joplin ui blank in jopin version 2.9.17, could you please fix it?

**Comment by ScriptInfra** [comment]
Could you upload a screenshot of what you are seeing? I'm not experiencing this issue.

**Comment by SuzanneHuang** [comment]
I am seeing this:
![94Y@`S7I8B~5}86N`LL1BHD](https://user-images.githubusercontent.com/31004006/208234550-43eea7e5-eca3-4594-8157-80a0dd8e0095.png)
I have found when I delete this plugin in [user profile]\plugins directory, then UI becomes ok.

**Comment by ScriptInfra** [comment]
Is your issue resolved after removing the plugins directory or did it come back after reinstalling the plugin? If the issue is still present you might try reinstalling Joplin and removing the plugins directory at the same time, and making sure all other plugins are disabled.

**Comment by SuzanneHuang** [comment]
Oh, It may be caused by the interaction of this plugin and other plugins. When there is only this plugin, the UI is normal.

**Comment by andrejilderda** [comment]
Thanks for the feedback!

Just in case this happens again in the future and you want to access your notes, know that you can always disable all plugins easily by running Joplin in safe mode: `Help` › `Toggle safe mode`.
