### ISSUE TITLE
Theme Does not Honor Notebook Image Files

### ISSUE THREAD

**Issue by ScriptInfra** [andrejilderda/joplin-macos-native-theme#89]
Hello! As discovered on the megathread, it seems the theme does not honor uploaded files as seen in the screenshot below. The folder icon is still present, even though a notebook icon has been set.

![image](https://user-images.githubusercontent.com/63025323/208351658-625929f1-0028-4983-9d7f-9169d412d9d2.png)

**Comment by andrejilderda** [comment]
@ScriptInfra This should be fixed in the new version. Let me know if this worked for you!

**Comment by ScriptInfra** [comment]
This looks to be fixed, thanks so much @andrejilderda!
