### ISSUE TITLE
Custom Folder Image Sizing Inconsistent

### ISSUE THREAD

**Issue by ScriptInfra** [andrejilderda/joplin-macos-native-theme#92]
Thanks for all the work supporting custom images for notebooks. Hopefully this is the last update needed..

Currently the sizing of the custom image is not consistent with that of Joplin without a theme applied. The custom image appears too large (or maybe the folder icon is slightly too small), and the spacing between the custom image and the name of the notebook is too small. Please see the below screenshots for the discrepancy:

![Screenshot 2022-12-21 at 4 53 15 PM](https://user-images.githubusercontent.com/63025323/209013125-c0cba490-fcf1-4d54-b6fe-d770f7412e46.png)

![Screenshot 2022-12-21 at 4 52 48 PM](https://user-images.githubusercontent.com/63025323/209013137-c28cbd20-970b-41ff-a8c9-d20c470dd56e.png)

**Comment by andrejilderda** [comment]
This should be fixed in v.1.3.11!
