### ISSUE TITLE
A tag icon is displayed when an emoji is used to the left of the tag text

### ISSUE THREAD

**Issue by broslavski** [andrejilderda/joplin-macos-native-theme#93]
The essence of the problem is in the title. In the native Joplin theme, when an emoji is inserted to the left of the tag text, the tag icon disappears. In the Joplin MacOS Native Theme this does not happen.
How can this problem be fixed? Maybe there are some custom style settings.

**Comment by andrejilderda** [comment]
Hi @broslavski, this is what I see in the sidebar:

With the theme enabled:
<img width="225" alt="image" src="https://user-images.githubusercontent.com/487182/209718644-b44fba63-0a58-4417-95d1-6d79066897bb.png">

And without:
<img width="224" alt="image" src="https://user-images.githubusercontent.com/487182/209718598-8ae77001-31d7-41f5-9332-71cec8a36530.png">

What did you expect? That the tag icon was replaced when an emoji was used inside the tag?

**Comment by broslavski** [comment]
Yes. Exactly.

**Comment by andrejilderda** [comment]
Ah, I see. Unfortunately it's impossible for me to fix, since the emoji is not in a different element than the rest of the tag. That being said, to me it's not different than Joplin's default behavior.

**Comment by broslavski** [comment]
Yes, I noticed. By default, there are just no icons for the tags. It's just text.
