### ISSUE TITLE
Macos主题卡死joplin的问题依然没有解决

### ISSUE THREAD

**Issue by abcmiao** [andrejilderda/joplin-macos-native-theme#98]
更新最新的joplin2.10.2了，如果那个文件夹图标一设置。joplin过一会就会卡死。后台占用CPU变多，风扇狂转。退不出joplin。无法进行操作，这个问题从2.9.17就出现了，为啥至今没人解决？

**Comment by abcmiao** [comment]
重新安装了macos主题插件，重新设置了图标，好像解决了

**Comment by abcmiao** [comment]
macOS系统M1电脑上还是不行

**Comment by abcmiao** [comment]
这个主题很棒，是我坚持用joplin的一大因素。

**Comment by benmordecai** [comment]
Workaround is to use emojis in the notebook name with no custom icon

**Comment by abcmiao** [comment]
> 解决方法是在笔记本名称中使用表情符号，而不使用自定义图标

是的，我后来发现了
