### ISSUE TITLE
Links are almost invisible for macOS theme in yellow on white

### ISSUE THREAD

**Issue by beatrixwillius** [andrejilderda/joplin-macos-native-theme#99]
Using the current version of Joplin (2.10.10 (prod, darwin)) and the current version of the macOS theme all links show up in yellow on white which makes them almost invisible. The links are blue without the theme. I get the yellow on white for both Ventura and my old High Sierra.

<img width="327" alt="Screenshot 2023-04-16 at 11 59 57" src="https://user-images.githubusercontent.com/1361928/232291779-79e08058-76f1-48d9-b35c-eab20f244057.png">

**Comment by andrejilderda** [comment]
Hi @beatrixwillius , it's a bit unfortunate but not all themes offered by Codemirror (the Markdown editor that Joplin is using under the hood) are optimised for contrast. The light theme you're using `3024-light` is one of them. You can however easily select another theme under Joplin settings › macOS theme › Markdown editor light (needs a restart after applying). Does that solve your issue?

**Comment by beatrixwillius** [comment]
Thanks, that did the trick!
